export const useThrowError = () => {
  throw new Error("Something went wrong. Please try again or later");
};
